#-------------------------------------------------
#   About - See Updates and Notes at bottom of script for more information.
#-------------------------------------------------

'''
Searches a given directory for all jil files that contain a search values found in find_replace_strings dictionary object.

The Keys are strings to search for, and the values are what replaces those strings in the duplciate text.
'''

#-------------------------------------------------
#   Imports
#-------------------------------------------------

#-------------------------------------------------
#   Variables
#-------------------------------------------------

output_log_file = "C:\\Users\\jlemaster3\\OneDrive - Gainwell Technologies\\Documents\\_Ticket_Repo\\RITM0150789\\NPR_RCG_log.txt"


DEVC_RCG_list = [ "TCANNUALLY_MCODWA_WORKDAY", "TCBIWEEKLY_MONDAY", "TCDAILY5_MON_THRU_FRI", "TCDAILY7", "TCELG_MONTHLY_3RD", "TCICSIS_NON_FRIDAY_HOLIDAY", "TCMGD_MONTHLY_3RD", "TCMGD_MONTHLY_820", "TCMONTHLY_10TH", "TCMONTHLY_15TH", "TCMONTHLY_16TH", "TCMONTHLY_18TH", "TCMONTHLY_1ST", "TCMONTHLY_1ST_AND_15TH", "TCMONTHLY_1ST_MONDAY", "TCMONTHLY_1ST_SUNDAY", "TCMONTHLY_1ST_WRKDAY", "TCMONTHLY_20TH", "TCMONTHLY_23RD", "TCMONTHLY_25TH", "TCMONTHLY_2ND", "TCMONTHLY_2ND_FRIDAY", "TCMONTHLY_2_TO_5_WKDY_EXTCAL", "TCMONTHLY_3RD", "TCMONTHLY_3RD_MONDAY", "TCMONTHLY_3RD_SUNDAY", "TCMONTHLY_3RD_WEDNESDAY", "TCMONTHLY_4TH", "TCMONTHLY_4TH_MONDAY", "TCMONTHLY_4TH_SUN", "TCMONTHLY_5TH", "TCMONTHLY_7TH", "TCMONTHLY_9TH", "TCMONTHLY_HID", "TCMONTHLY_KEES", "TCMONTHLY_LAST_DAY", "TCMONTHLY_LAST_FRIDAY", "TCMONTHLY_LAST_SATURDAY", "TCMONTHLY_LAST_THURSDAY", "TCMONTHLY_MAR", "TCMONTHLY_MCODWA_WORKDAY", "TCMONTHLY_RISK_COV", "TCMONTHLY_RPTS", "TCMONTHLY_RPTS15", "TCPBCYEARLY_DEC1ST", "TCPBCYEARLY_JAN1ST", "TCPBC_MONTHLY", "TCQUARTERLY_15TH", "TCQUARTERLY_1ST", "TCQUARTERLY_1ST_MONDAY", "TCQUARTERLY_25TH", "TCQUARTERLY_2ND", "TCQUARTERLY_4TH_TUESDAY", "TCQUARTERLY_7TH", "TCQUARTERLY_LASTDAY", "TCQUARTERLY_MAR", "TCQUARTERLY_MCODWA_WORKDAY", "TCSEMIANNUAL_LAST_THURSDAY", "TCSEMIANNUAL_MCODWA_WORKDAY", "TCWEEKLY_CLIA", "TCWEEKLY_FDB", "TCWEEKLY_FIN", "TCWEEKLY_FIN_CYCLE", "TCWEEKLY_FRIDAY", "TCYEARLY_ADAP15", "TCYEARLY_AUWVR", "TCYEARLY_DEC31ST", "TCYEARLY_FEWVR", "TCYEARLY_IDDWVR", "TCYEARLY_JAN01", "TCYEARLY_JAN25TH", "TCYEARLY_JULY1ST", "TCYEARLY_LAST_FRIDAY", "TCYEARLY_MAR1ST", "TCYEARLY_OCT10TH", "TCYEARLY_OCT1ST", "TCYEARLY_PDWVR", "TCYEARLY_SEWVR", "TCYEARLY_TAWVR", "TCYEARLY_TBIWVR", "TC_ANNUAL_CLM_SFY" ]
DEVB_RCG_list = [ "TBANNUALLY_MCODWA_WORKDAY", "TBBIWEEKLY_MONDAY", "TBDAILY5_MON_THRU_FRI", "TBDAILY7", "TBELG_MONTHLY_3RD", "TBICSIS_NON_FRIDAY_HOLIDAY", "TBMGD_MONTHLY_3RD", "TBMGD_MONTHLY_820", "TBMONTHLY_10TH", "TBMONTHLY_15TH", "TBMONTHLY_16TH", "TBMONTHLY_18TH", "TBMONTHLY_1ST", "TBMONTHLY_1ST_AND_15TH", "TBMONTHLY_1ST_MONDAY", "TBMONTHLY_1ST_SUNDAY", "TBMONTHLY_1ST_WRKDAY", "TBMONTHLY_20TH", "TBMONTHLY_23RD", "TBMONTHLY_25TH", "TBMONTHLY_2ND", "TBMONTHLY_2ND_FRIDAY", "TBMONTHLY_2_TO_5_WKDY_EXTCAL", "TBMONTHLY_3RD", "TBMONTHLY_3RD_MONDAY", "TBMONTHLY_3RD_SUNDAY", "TBMONTHLY_3RD_WEDNESDAY", "TBMONTHLY_4TH", "TBMONTHLY_4TH_MONDAY", "TBMONTHLY_4TH_SUN", "TBMONTHLY_5TH", "TBMONTHLY_7TH", "TBMONTHLY_9TH", "TBMONTHLY_HID", "TBMONTHLY_KEES", "TBMONTHLY_LAST_DAY", "TBMONTHLY_LAST_FRIDAY", "TBMONTHLY_LAST_SATURDAY", "TBMONTHLY_LAST_THURSDAY", "TBMONTHLY_MAR", "TBMONTHLY_MCODWA_WORKDAY", "TBMONTHLY_MEC", "TBMONTHLY_RISK_COV", "TBMONTHLY_RPTS", "TBMONTHLY_RPTS15", "TBPBCYEARLY_DEC1ST", "TBPBCYEARLY_JAN1ST", "TBPBC_MONTHLY", "TBQUARTERLY_15TH", "TBQUARTERLY_1ST", "TBQUARTERLY_1ST_MONDAY", "TBQUARTERLY_25TH", "TBQUARTERLY_2ND", "TBQUARTERLY_4TH_TUESDAY", "TBQUARTERLY_7TH", "TBQUARTERLY_LASTDAY", "TBQUARTERLY_MAR", "TBQUARTERLY_MCODWA_WORKDAY", "TBSEMIANNUAL_LAST_THURSDAY", "TBSEMIANNUAL_MCODWA_WORKDAY", "TBWEEKLY_CLIA", "TBWEEKLY_FDB", "TBWEEKLY_FIN", "TBWEEKLY_FIN_CYCLE", "TBWEEKLY_FRIDAY", "TBYEARLY_ADAP15", "TBYEARLY_AUWVR", "TBYEARLY_DEC31ST", "TBYEARLY_FEWVR", "TBYEARLY_IDDWVR", "TBYEARLY_JAN01", "TBYEARLY_JAN25TH", "TBYEARLY_JULY1ST", "TBYEARLY_LAST_FRIDAY", "TBYEARLY_MAR1ST", "TBYEARLY_OCT10TH", "TBYEARLY_OCT1ST", "TBYEARLY_PDWVR", "TBYEARLY_SEWVR", "TBYEARLY_TAWVR", "TBYEARLY_TBIWVR", "TB_ANNUAL_CLM_SFY" ]
SITC_RCG_list = [ "MCANNUALLY_MCODWA_WORKDAY", "MCBIWEEKLY_MONDAY", "MCDAILY5_MON_THRU_FRI", "MCDAILY7", "MCELG_MONTHLY_3RD", "MCICSIS_NON_FRIDAY_HOLIDAY", "MCMGD_MONTHLY_3RD", "MCMGD_MONTHLY_820", "MCMONTHLY_10TH", "MCMONTHLY_15TH", "MCMONTHLY_16TH", "MCMONTHLY_18TH", "MCMONTHLY_1ST", "MCMONTHLY_1ST_AND_15TH", "MCMONTHLY_1ST_MONDAY", "MCMONTHLY_1ST_SUNDAY", "MCMONTHLY_1ST_WRKDAY", "MCMONTHLY_20TH", "MCMONTHLY_23RD", "MCMONTHLY_25TH", "MCMONTHLY_2ND", "MCMONTHLY_2ND_FRIDAY", "MCMONTHLY_2_TO_5_WKDY_EXTCAL", "MCMONTHLY_3RD", "MCMONTHLY_3RD_MONDAY", "MCMONTHLY_3RD_SUNDAY", "MCMONTHLY_3RD_WEDNESDAY", "MCMONTHLY_4TH", "MCMONTHLY_4TH_MONDAY", "MCMONTHLY_4TH_SUN", "MCMONTHLY_5TH", "MCMONTHLY_7TH", "MCMONTHLY_9TH", "MCMONTHLY_HID", "MCMONTHLY_KEES", "MCMONTHLY_LAST_DAY", "MCMONTHLY_LAST_FRIDAY", "MCMONTHLY_LAST_SATURDAY", "MCMONTHLY_LAST_THURSDAY", "MCMONTHLY_MAR", "MCMONTHLY_MCODWA_WORKDAY", "MCMONTHLY_RISK_COV", "MCMONTHLY_RPTS", "MCMONTHLY_RPTS15", "MCPBCYEARLY_DEC1ST", "MCPBCYEARLY_JAN1ST", "MCPBC_MONTHLY", "MCQUARTERLY_15TH", "MCQUARTERLY_1ST", "MCQUARTERLY_1ST_MONDAY", "MCQUARTERLY_25TH", "MCQUARTERLY_2ND", "MCQUARTERLY_4TH_TUESDAY", "MCQUARTERLY_7TH", "MCQUARTERLY_LASTDAY", "MCQUARTERLY_MAR", "MCQUARTERLY_MCODWA_WORKDAY", "MCSEMIANNUAL_LAST_THURSDAY", "MCSEMIANNUAL_MCODWA_WORKDAY", "MCWEEKLY_CLIA", "MCWEEKLY_FDB", "MCWEEKLY_FIN", "MCWEEKLY_FIN_CYCLE", "MCWEEKLY_FRIDAY", "MCYEARLY_ADAP15", "MCYEARLY_AUWVR", "MCYEARLY_DEC31ST", "MCYEARLY_FEWVR", "MCYEARLY_IDDWVR", "MCYEARLY_JAN01", "MCYEARLY_JAN25TH", "MCYEARLY_JULY1ST", "MCYEARLY_LAST_FRIDAY", "MCYEARLY_MAR1ST", "MCYEARLY_OCT10TH", "MCYEARLY_OCT1ST", "MCYEARLY_PDWVR", "MCYEARLY_SEWVR", "MCYEARLY_TAWVR", "MCYEARLY_TBIWVR", "MC_ANNUAL_CLM_SFY" ]
SITB_RCG_list = [ "MBANNUALLY_MCODWA_WORKDAY", "MBBIWEEKLY_MONDAY", "MBDAILY5_MON_THRU_FRI", "MBDAILY7", "MBELG_MONTHLY_3RD", "MBICSIS_NON_FRIDAY_HOLIDAY", "MBMGD_MONTHLY_3RD", "MBMGD_MONTHLY_820", "MBMONTHLY_10TH", "MBMONTHLY_15TH", "MBMONTHLY_16TH", "MBMONTHLY_18TH", "MBMONTHLY_1ST", "MBMONTHLY_1ST_AND_15TH", "MBMONTHLY_1ST_MONDAY", "MBMONTHLY_1ST_SUNDAY", "MBMONTHLY_1ST_WRKDAY", "MBMONTHLY_20TH", "MBMONTHLY_23RD", "MBMONTHLY_25TH", "MBMONTHLY_2ND", "MBMONTHLY_2ND_FRIDAY", "MBMONTHLY_2_TO_5_WKDY_EXTCAL", "MBMONTHLY_3RD", "MBMONTHLY_3RD_MONDAY", "MBMONTHLY_3RD_SUNDAY", "MBMONTHLY_3RD_WEDNESDAY", "MBMONTHLY_4TH", "MBMONTHLY_4TH_MONDAY", "MBMONTHLY_4TH_SUN", "MBMONTHLY_5TH", "MBMONTHLY_7TH", "MBMONTHLY_9TH", "MBMONTHLY_HID", "MBMONTHLY_KEES", "MBMONTHLY_LAST_DAY", "MBMONTHLY_LAST_FRIDAY", "MBMONTHLY_LAST_SATURDAY", "MBMONTHLY_LAST_THURSDAY", "MBMONTHLY_MAR", "MBMONTHLY_MCODWA_WORKDAY", "MBMONTHLY_RISK_COV", "MBMONTHLY_RPTS", "MBMONTHLY_RPTS15", "MBPBCYEARLY_DEC1ST", "MBPBCYEARLY_JAN1ST", "MBPBC_MONTHLY", "MBQUARTERLY_15TH", "MBQUARTERLY_1ST", "MBQUARTERLY_1ST_MONDAY", "MBQUARTERLY_25TH", "MBQUARTERLY_2ND", "MBQUARTERLY_4TH_TUESDAY", "MBQUARTERLY_7TH", "MBQUARTERLY_LASTDAY", "MBQUARTERLY_MAR", "MBQUARTERLY_MCODWA_WORKDAY", "MBSEMIANNUAL_LAST_THURSDAY", "MBSEMIANNUAL_MCODWA_WORKDAY", "MBWEEKLY_CLIA", "MBWEEKLY_FDB", "MBWEEKLY_FIN", "MBWEEKLY_FIN_CYCLE", "MBWEEKLY_FRIDAY", "MBYEARLY_ADAP15", "MBYEARLY_AUWVR", "MBYEARLY_DEC31ST", "MBYEARLY_FEWVR", "MBYEARLY_IDDWVR", "MBYEARLY_JAN01", "MBYEARLY_JAN25TH", "MBYEARLY_JULY1ST", "MBYEARLY_LAST_FRIDAY", "MBYEARLY_MAR1ST", "MBYEARLY_OCT10TH", "MBYEARLY_OCT1ST", "MBYEARLY_PDWVR", "MBYEARLY_SEWVR", "MBYEARLY_TAWVR", "MBYEARLY_TBIWVR", "MB_ANNUAL_CLM_SFY" ]
UATC_RCG_list = [ "ACANNUALLY_MCODWA_WORKDAY", "ACBIWEEKLY_MONDAY", "ACDAILY5_MON_THRU_FRI", "ACDAILY7", "ACELG_MONTHLY_3RD", "ACICSIS_NON_FRIDAY_HOLIDAY", "ACMGD_MONTHLY_3RD", "ACMGD_MONTHLY_820", "ACMONTHLY_10TH", "ACMONTHLY_15TH", "ACMONTHLY_16TH", "ACMONTHLY_18TH", "ACMONTHLY_1ST", "ACMONTHLY_1ST_AND_15TH", "ACMONTHLY_1ST_MONDAY", "ACMONTHLY_1ST_SUNDAY", "ACMONTHLY_1ST_WRKDAY", "ACMONTHLY_20TH", "ACMONTHLY_23RD", "ACMONTHLY_25TH", "ACMONTHLY_2ND", "ACMONTHLY_2ND_FRIDAY", "ACMONTHLY_2_TO_5_WKDY_EXTCAL", "ACMONTHLY_3RD", "ACMONTHLY_3RD_MONDAY", "ACMONTHLY_3RD_SUNDAY", "ACMONTHLY_3RD_WEDNESDAY", "ACMONTHLY_4TH", "ACMONTHLY_4TH_MONDAY", "ACMONTHLY_4TH_SUN", "ACMONTHLY_5TH", "ACMONTHLY_7TH", "ACMONTHLY_9TH", "ACMONTHLY_HID", "ACMONTHLY_KEES", "ACMONTHLY_LAST_DAY", "ACMONTHLY_LAST_FRIDAY", "ACMONTHLY_LAST_SATURDAY", "ACMONTHLY_LAST_THURSDAY", "ACMONTHLY_MAR", "ACMONTHLY_MCODWA_WORKDAY", "ACMONTHLY_MEC", "ACMONTHLY_RISK_COV", "ACMONTHLY_RPTS", "ACMONTHLY_RPTS15", "ACPBCYEARLY_DEC1ST", "ACPBCYEARLY_JAN1ST", "ACPBC_MONTHLY", "ACQUARTERLY_15TH", "ACQUARTERLY_1ST", "ACQUARTERLY_1ST_MONDAY", "ACQUARTERLY_25TH", "ACQUARTERLY_2ND", "ACQUARTERLY_4TH_TUESDAY", "ACQUARTERLY_7TH", "ACQUARTERLY_LASTDAY", "ACQUARTERLY_MAR", "ACQUARTERLY_MCODWA_WORKDAY", "ACSEMIANNUAL_LAST_THURSDAY", "ACSEMIANNUAL_MCODWA_WORKDAY", "ACWEEKLY_CLIA", "ACWEEKLY_FDB", "ACWEEKLY_FIN", "ACWEEKLY_FIN_CYCLE", "ACWEEKLY_FRIDAY", "ACYEARLY_ADAP15", "ACYEARLY_AUWVR", "ACYEARLY_DEC31ST", "ACYEARLY_FEWVR", "ACYEARLY_IDDWVR", "ACYEARLY_JAN01", "ACYEARLY_JAN25TH", "ACYEARLY_JULY1ST", "ACYEARLY_LAST_FRIDAY", "ACYEARLY_MAR1ST", "ACYEARLY_OCT10TH", "ACYEARLY_OCT1ST", "ACYEARLY_PDWVR", "ACYEARLY_SEWVR", "ACYEARLY_TAWVR", "ACYEARLY_TBIWVR", "AC_ANNUAL_CLM_SFY" ]
UATB_RCG_list = [ "ABBIWEEKLY_MONDAY", "ABDAILY5_MON_THRU_FRI", "ABDAILY7", "ABELG_MONTHLY_3RD", "ABICSIS_NON_FRIDAY_HOLIDAY", "ABMGD_MONTHLY_3RD", "ABMGD_MONTHLY_820", "ABMONTHLY_10TH", "ABMONTHLY_15TH", "ABMONTHLY_16TH", "ABMONTHLY_18TH", "ABMONTHLY_1ST", "ABMONTHLY_1ST_AND_15TH", "ABMONTHLY_1ST_MONDAY", "ABMONTHLY_1ST_SUNDAY", "ABMONTHLY_1ST_WRKDAY", "ABMONTHLY_20TH", "ABMONTHLY_23RD", "ABMONTHLY_25TH", "ABMONTHLY_2ND", "ABMONTHLY_2ND_FRIDAY", "ABMONTHLY_2_TO_5_WKDY_EXTCAL", "ABMONTHLY_3RD", "ABMONTHLY_3RD_MONDAY", "ABMONTHLY_3RD_SUNDAY", "ABMONTHLY_3RD_WEDNESDAY", "ABMONTHLY_4TH", "ABMONTHLY_4TH_MONDAY", "ABMONTHLY_4TH_SUN", "ABMONTHLY_5TH", "ABMONTHLY_7TH", "ABMONTHLY_9TH", "ABMONTHLY_HID", "ABMONTHLY_KEES", "ABMONTHLY_LAST_DAY", "ABMONTHLY_LAST_FRIDAY", "ABMONTHLY_LAST_SATURDAY", "ABMONTHLY_LAST_THURSDAY", "ABMONTHLY_MAR", "ABMONTHLY_MCODWA_WORKDAY", "ABMONTHLY_RISK_COV", "ABMONTHLY_RPTS", "ABMONTHLY_RPTS15", "ABPBCYEARLY_DEC1ST", "ABPBCYEARLY_JAN1ST", "ABPBC_MONTHLY", "ABQUARTERLY_15TH", "ABQUARTERLY_1ST", "ABQUARTERLY_1ST_MONDAY", "ABQUARTERLY_25TH", "ABQUARTERLY_2ND", "ABQUARTERLY_4TH_TUESDAY", "ABQUARTERLY_7TH", "ABQUARTERLY_LASTDAY", "ABQUARTERLY_MAR", "ABQUARTERLY_MCODWA_WORKDAY", "ABSEMIANNUAL_LAST_THURSDAY", "ABSEMIANNUAL_MCODWA_WORKDAY", "ABWEEKLY_CLIA", "ABWEEKLY_FDB", "ABWEEKLY_FIN", "ABWEEKLY_FIN_CYCLE", "ABWEEKLY_FRIDAY", "ABYEARLY_ADAP15", "ABYEARLY_AUWVR", "ABYEARLY_DEC31ST", "ABYEARLY_FEWVR", "ABYEARLY_IDDWVR", "ABYEARLY_JAN01", "ABYEARLY_JAN25TH", "ABYEARLY_JULY1ST", "ABYEARLY_LAST_FRIDAY", "ABYEARLY_MAR1ST", "ABYEARLY_OCT10TH", "ABYEARLY_OCT1ST", "ABYEARLY_PDWVR", "ABYEARLY_SEWVR", "ABYEARLY_TAWVR", "ABYEARLY_TBIWVR", "AB_ANNUAL_CLM_SFY" ]

ENV_RCG_groups = {
    "DEV":{
        "ENV_Prefix":["TC", "TB"],
        "RCG_List":[DEVC_RCG_list, DEVB_RCG_list]
    },
    "SIT":{
        "ENV_Prefix":["MC", "MB"],
        "RCG_List":[SITC_RCG_list, SITB_RCG_list]
    },
    "UAT":{
        "ENV_Prefix":["AC", "AB"],
        "RCG_List":[UATC_RCG_list, UATB_RCG_list]
    }
}

#-------------------------------------------------
#   Functions
#-------------------------------------------------

def get_diff_listA_listB (list_a:list[str], list_b:list[str])-> list[str]:    
    return list(set(list_a) - set(list_b))

def remove_previx_from_list_values (source_list:list[str], prefix:str)->list[str]:
    _prefix_len = len(prefix)
    _holder = []
    for _str in source_list:
        if (len(_str) > _prefix_len) and (prefix.upper() == _str.upper()[:_prefix_len]):
            _holder.append(_str[_prefix_len:])
    return _holder

#-------------------------------------------------
#   Initialize Script
#-------------------------------------------------

if __name__ == "__main__":

    _output_log_holder = []
    _output_log_holder.append(f"Gathering list of RCG diffrences between sets of Environments")
    _output_log_holder.append('-'*100)
    for _env, _grpSetting in ENV_RCG_groups.items():
        prefix_a = _grpSetting['ENV_Prefix'][0]
        prefix_b = _grpSetting['ENV_Prefix'][1]
        list_a = _grpSetting['RCG_List'][0]
        list_b = _grpSetting['RCG_List'][1]
        list_a_noPrefix = remove_previx_from_list_values (list_a, prefix_a)
        list_b_noPrefix = remove_previx_from_list_values (list_b, prefix_b)
        diff_A_B = get_diff_listA_listB (list_a_noPrefix, list_b_noPrefix)

        _output_log_holder.append(f"Soruce Environment : '{str(_env).upper()}'")
        _output_log_holder.append(f"  list_A Prefix : '{prefix_a}'")
        _output_log_holder.append(f"  list_A : [{len(list_a)}] {', '.join(list_a)}")
        #_output_log_holder.append(f"  list_A : [{len(list_a_noPrefix)}] {', '.join(list_a_noPrefix)}")
        _output_log_holder.append("\n")
        _output_log_holder.append(f"  list_B Prefix : '{prefix_b}'")
        _output_log_holder.append(f"  list_B : [{len(list_b)}] {', '.join(list_b)}")
        #_output_log_holder.append(f"  list_B : [{len(list_b_noPrefix)}] {', '.join(list_b_noPrefix)}")
        _output_log_holder.append("\n")
        _output_log_holder.append(f"  RCG to Create in ENV B for {_env} with Prefix ({prefix_b}) : [{len(diff_A_B)}] ( {', '.join(f'{prefix_b}{_s}' for _s in diff_A_B)} )")
        _output_log_holder.append('-'*100)

    with open (output_log_file, 'w') as _log_file:
        _log_file.write("\n".join(_output_log_holder))
    
    print (f"Done processing")